export const GLOBAL_DATA_LOADING = 'GLOBAL_DATA_LOADING';
export const GLOBAL_DATA_SUCCESS = 'GLOBAL_DATA_SUCCESS';
export const GLOBAL_DATA_ERROR = 'GLOBAL_DATA_ERROR';
export const COUNTRIES_DATA_LOADING = 'COUNTRIES_DATA_LOADING';
export const COUNTRIES_DATA_SUCCESS = 'COUNTRIES_DATA_SUCCESS';
export const COUNTRIES_DATA_ERROR = 'COUNTRIES_DATA_ERROR';
export const COUNTRIES_DATA_SORT = 'COUNTRIES_DATA_SORT';
