export const GLOBAL_DATA_LOADING = 'DATA_LOADING';
export const GLOBAL_DATA_SUCCESS = 'DATA_SUCCESS';
export const GLOBAL_DATA_ERROR = 'DATA_ERROR';
export const COUNTRIES_DATA_LOADING = 'DATA_LOADING';
export const COUNTRIES_DATA_SUCCESS = 'DATA_SUCCESS';
export const COUNTRIES_DATA_ERROR = 'DATA_ERROR';
